### ISSUE TITLE
Delete test data before running tests

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#151]

**Comment by Cahllagerfeld** [comment]
>Delete a collection
>
>Send a DELETE request to /v2/schemas/namespaces/{namespace_name}/collections/{collection_name} to delete a collection. All >data will be deleted along with the collection schema.
>
>curl -L \
>-X DELETE 'http://localhost:8082/v2/namespaces/myworld/collections/fitness' \
>--header "X-Cassandra-Token: $AUTH_TOKEN" \
>--header 'Content-Type: application/json'

Thats from the [stargate-docs](https://stargate.io/docs/stargate/1.0/developers-guide/document-using.html)

**Comment by eddiejaoude** [comment]
Awesome, we can drop all the collections!

Looking at the docs, we might be able just to drop the keyspace `test`, that way we don't have to manage the collection names
https://stargate.io/docs/stargate/1.0/quickstart/quick_start-rest.html#_create_or_delete_keyspace_and_table_schema

**Comment by eddiejaoude** [comment]
Could this be added to the same library that creates the keyspace, but has a delete flag?

**Comment by Cahllagerfeld** [comment]
I added this to the package, so it should work against the local-stargate container.
I just realized another thing: 

the `@before()` hook seems to be executed before every single test.
```ts
  @before()
  public async before(): Promise<void> {
    if (process.env.STARGATE_BASEURL) {
      await new Promise((resolve) => {
        exec('npm run prestart', (error, stdout, stderr) => {
          if (error) {
            console.warn(error);
          }
          resolve(stdout ? stdout : stderr);
        });
      });
    }
...
```
This means the `exec` with the `npm run prestart` runs before every test. That causes way too much traffic and may be the reason for the heavy load on my computer.
Is there actually a spot where I can put an async function that it only get exectued once, when initially starting the tests and not before every test?

**Comment by eddiejaoude** [comment]
> Defines a hook which is run before all scenarios

I think it is possible to use `BeforeAll` https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md#beforealloptions-fn

**Comment by eddiejaoude** [comment]
the first time I run the tests I get ...

```
Error: a BeforeAll hook errored, process exiting: test/step-definitions/requests.ts:10: function timed out, ensure the promise resolves within 5000 milliseconds
    at /Users/ej/Downloads/repos/EddieHub/api/node_modules/cucumber/lib/runtime/index.js:68:19
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ej/Downloads/repos/EddieHub/api/node_modules/cucumber/lib/runtime/index.js:26:103)
    at _next (/Users/ej/Downloads/repos/EddieHub/api/node_modules/cucumber/lib/runtime/index.js:28:194)
caused by: Error: function timed out, ensure the promise resolves within 5000 milliseconds
    at Timeout._onTimeout (/Users/ej/Downloads/repos/EddieHub/api/node_modules/cucumber/lib/user_code_runner.js:81:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

and the 2nd time I get ...

```
@calendar
Feature: calendar module

  @calendar
  Scenario: add a new event
    Given authorisation
    When make a POST request to "/calendar" with:
      │ name        │ "Livestream XY"                       │
      │ description │ "descriptive Description"             │
      │ url         │ "https://domain.com"                  │
      │ platform    │ "YouTube"                             │
      │ author      │ {"platform":"discord","uid":"hubber"} │
      │ startDate   │ "2021-01-01T00:00:00.000Z"            │
      │ endDate     │ "2021-01-01T00:00:00.000Z"            │
    ✖ failed
      Error: function timed out, ensure the promise resolves within 5000 milliseconds
          at Timeout._onTimeout (/Users/ej/Downloads/repos/EddieHub/api/node_modules/cucumber/lib/user_code_runner.js:81:20)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7)
    And the response should contain:
      │ documentId │ "TYPE:ID" │
    - skipped
    When make a GET request to "/calendar/{id}"
    - skipped
    Then the response status code should be 200
    - skipped
    And the response should contain:
      │ name        │ "Livestream XY"                       │
      │ description │ "descriptive Description"             │
      │ url         │ "https://domain.com"                  │
      │ platform    │ "YouTube"                             │
      │ author      │ {"platform":"discord","uid":"hubber"} │
      │ startDate   │ "2021-01-01T00:00:00.000Z"            │
      │ endDate     │ "2021-01-01T00:00:00.000Z"            │
      │ createdOn   │ "TYPE:DATE"                           │
      │ updatedOn   │ "TYPE:DATE"                           │
    - skipped
```

There might be an unhandled promise 🤔

**Comment by eddiejaoude** [comment]
Running some tests, it looks like the `delete` took much more than 5s to complete (the `create` is fast though)

**create**
```
               _                                   _                                    _          
  ___    ___  | |_   _   _   _ __            ___  | |_    __ _   _ __    __ _    __ _  | |_    ___ 
 / __|  / _ \ | __| | | | | | '_ \   _____  / __| | __|  / _` | | '__|  / _` |  / _` | | __|  / _ \
 \__ \ |  __/ | |_  | |_| | | |_) | |_____| \__ \ | |_  | (_| | | |    | (_| | | (_| | | |_  |  __/
 |___/  \___|  \__|  \__,_| | .__/          |___/  \__|  \__,_| |_|     \__, |  \__,_|  \__|  \___|
                            |_|                                         |___/                      
Initialization started
Authentication successfull
stargate for keyspace eddiehub initialized successfully
npm run stargate:keyspace:create  0.26s user 0.05s system 34% cpu 0.922 total
➜  api git:(main) ✗ 
```

**delete**
```
               _                                   _                                    _          
  ___    ___  | |_   _   _   _ __            ___  | |_    __ _   _ __    __ _    __ _  | |_    ___ 
 / __|  / _ \ | __| | | | | | '_ \   _____  / __| | __|  / _` | | '__|  / _` |  / _` | | __|  / _ \
 \__ \ |  __/ | |_  | |_| | | |_) | |_____| \__ \ | |_  | (_| | | |    | (_| | | (_| | | |_  |  __/
 |___/  \___|  \__|  \__,_| | .__/          |___/  \__|  \__,_| |_|     \__, |  \__,_|  \__|  \___|
                            |_|                                         |___/                      
Initialization started
Authentication successfull
stargate for keyspace eddiehub deleted successfully
npm run stargate:keyspace:delete  0.38s user 0.07s system 4% cpu 10.046 total
➜  api git:(main) ✗ 
```

**Comment by eddiejaoude** [comment]
I think I fixed it by increasing the timeout of Cucumber https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md

**Comment by Cahllagerfeld** [comment]
> 
> 
> I think I fixed it by increasing the timeout of Cucumber https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md
> 
> ```
> 42 scenarios (42 passed)
> 225 steps (225 passed)
> 1m04.139s
> ```

just did exatcly the same

```diff

+ setDefaultTimeout(60 * 1000); \

BeforeAll(async () => {
  if (process.env.STARGATE_BASEURL) {
    try {
      await new Promise((resolve) => {
        exec('npm run stargate:keyspace:delete', (error, stdout, stderr) => {
          if (error) {
            console.warn(error);
          }
          resolve(stdout ? stdout : stderr);
        });
      });
    } catch (e) {
      console.log('keyspace not deleted');
    }
    await new Promise((resolve) => {
      exec('npm run stargate:keyspace:create', (error, stdout, stderr) => {
        if (error) {
          console.warn(error);
        }
        resolve(stdout ? stdout : stderr);
      });
    });
  }
});
```

**Comment by eddiejaoude** [comment]
Oh cool 👍 , I just created the PR https://github.com/EddieHubCommunity/api/pull/153

**Comment by Cahllagerfeld** [comment]
were moving along quite fast 💥

**Comment by eddiejaoude** [comment]
Thank you for your help 🔥
